/**
 * Default sidebars configuration for Portosaurus
 * This file is auto-generated and copied to user projects
 */

module.exports = {
  notes: [
    {
      type: "category",
      label: "Notes",
      link: { type: "doc", id: "index" },
      items: [
        {
          type: "autogenerated",
          dirName: ".",
        },
      ],
    },
  ],
};
