[tools]
uv = "latest"
"pipx:commitizen" = "latest"
bun = "latest"

[env]
_.path = './packages/cli/bin'
CZ_CONFIG = 'src/cz/cz.yaml'

[tasks]
bump = "cz --config $CZ_CONFIG  bump"
commit = "cz --config $CZ_CONFIG commit"
changelog = "cz --config $CZ_CONFIG changelog"
pr = "gh pr create"
