
const sidebar = {
  
  notes: [
    {
      type: 'category',
      label: 'Notes',
      link: { type: 'doc', id: 'index' },
      items: [
        {
          type: 'autogenerated',
          dirName: '.'
        }
      ]
    }
  ]
};


module.exports = sidebar;
