const sidebar = {
  notes: [
    {
      type: "category",
      label: "Notes",
      link: { type: "generated-index", slug: "/" },
      items: [{ type: "autogenerated", dirName: "." }],
    },
  ],
};
module.exports = sidebar;
