import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { spawn } from "child_process";
import { logger } from "./logger.mjs";
import { getDocuCmd } from "./packageManager.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const PortoRoot = path.resolve(__dirname, "../..");

/**
 * Write the ephemeral .portosaurus/docusaurus.config.mjs shim.
 */
export function writePortoConfigShim(UserRoot) {
  const dotDir = path.join(UserRoot, ".docusaurus", "portosaurus");
  fs.mkdirSync(dotDir, { recursive: true });

  const configJsAbsolute = path.join(UserRoot, "config.js").replace(/\\/g, "/");
  const createDocuConfAbsolute = path
    .resolve(PortoRoot, "src/core/buildDocuConfig.mjs")
    .replace(/\\/g, "/");

  const shimContent = `// Auto-generated by Portosaurus CLI — do not edit
/** @type {import('@docusaurus/types').Config} */
export default async function getConfig() {
  const { buildDocuConfig } = await import("file://${createDocuConfAbsolute}");
  const { usrConf } = await import("file://${configJsAbsolute}");
  return buildDocuConfig(usrConf, "${UserRoot.replace(/\\/g, "/")}");
}
`;

  const shimPath = path.join(dotDir, "docusaurus.config.js");
  fs.writeFileSync(shimPath, shimContent);
  logger.debug(`Config shim written to ${shimPath}`);

  return shimPath;
}

/**
 * Validate that the current directory is a Portosaurus project.
 */
export function validateProject(UserRoot) {
  const configPath = path.join(UserRoot, "config.js");
  if (!fs.existsSync(configPath)) {
    logger.log("");
    logger.error(
      "config.js not found. Are you in a Portosaurus project directory?",
    );
    process.exit(1);
  }
}

/**
 * Ensure essential user content directories exist.
 */
export function ensureContentDirs(UserRoot) {
  for (const dir of ["notes", "blog", "static"]) {
    fs.mkdirSync(path.join(UserRoot, dir), { recursive: true });
  }

  const notesIndex = path.join(UserRoot, "notes", "index.mdx");
  if (!fs.existsSync(notesIndex)) {
    fs.writeFileSync(
      notesIndex,
      `---\nhide_table_of_contents: true\n---\n\nimport NoteCards from "portosaurus/src/theme/components/NoteIndex/index.js";\n\n# Notes\n\n<NoteCards />\n`,
    );
    logger.debug("Created default notes/index.mdx");
  }
}

/**
 * Spawn a Docusaurus command and wait for it to complete.
 */
export function runDocusaurus(command, extraArgs, UserRoot, configPath) {
  const {
    command: cmd,
    args: pmArgs,
    packageManager,
  } = getDocuCmd(UserRoot);

  logger.info(`Running docusaurus ${command} (via ${packageManager})`);

  const finalArgs = [
    ...pmArgs,
    command,
    UserRoot,
    "--config",
    configPath,
    ...extraArgs,
  ];

  const child = spawn(cmd, finalArgs, {
    stdio: "inherit",
    cwd: UserRoot,
    env: { ...process.env, FORCE_COLOR: "true" },
  });

  return new Promise((resolve, reject) => {
    child.on("error", (err) => {
      logger.error(`Failed to run docusaurus ${command}: ${err.message}`);
      reject(err);
    });
    child.on("close", (code) => {
      if (code === 0) resolve();
      else process.exit(code);
    });
  });
}

// Recursively copy a directory and apply text replacements.
export function mirrorSync(src, dest, replacements = {}, ignores = []) {
  const ignoreSet = new Set(ignores);
  const textExtensions = new Set([
    ".js",
    ".mjs",
    ".json",
    ".md",
    ".mdx",
    ".yml",
    ".yaml",
    ".css",
    ".html",
    ".txt",
  ]);

  fs.mkdirSync(dest, { recursive: true });

  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (ignoreSet.has(entry.name)) continue;

    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      mirrorSync(srcPath, destPath, replacements, ignores);
    } else {
      const ext = path.extname(entry.name).toLowerCase();

      // If replacements exist and it's a known text file, process it
      if (Object.keys(replacements).length > 0 && textExtensions.has(ext)) {
        let content = fs.readFileSync(srcPath, "utf8");
        for (const [key, value] of Object.entries(replacements)) {
          // Replace all occurrences of {{key}}
          const regex = new RegExp(`\\{\\{${key}\\}\\}`, "g");
          content = content.replace(regex, value);
        }
        fs.writeFileSync(destPath, content);
      } else {
        fs.copyFileSync(srcPath, destPath); // Safe copy for binaries (images, etc) or when no replacements needed
      }
    }
  }
}
