import fs from "fs";
import path from "path";
import { spawn } from "child_process";
import { logger } from "./logger.mjs";
import { getDocuCmd } from "./packageManager.mjs";
import { PortoRoot } from "../core/constants.mjs";

/**
 * Write the ephemeral .portosaurus/docusaurus.config.mjs shim.
 */
export function writePortoConfigShim(UserRoot) {
  const dotDir = path.join(UserRoot, ".docusaurus", "portosaurus");
  fs.mkdirSync(dotDir, { recursive: true });

  const configYaml = ["config.yaml", "config.yml"].find((f) =>
    fs.existsSync(path.join(UserRoot, f)),
  );

  if (!configYaml) {
    logger.error("No config.yaml or config.yml found in project root.");
    process.exit(1);
  }

  const configYamlAbsolute = path
    .join(UserRoot, configYaml)
    .replace(/\\/g, "/");
  const createDocuConfAbsolute = path
    .resolve(PortoRoot, "src/core/buildDocuConfig.mjs")
    .replace(/\\/g, "/");

  const shimContent = `// Auto-generated by Portosaurus CLI — do not edit
import fs from "fs";
import yaml from "js-yaml";

/** @type {import('@docusaurus/types').Config} */
export default async function getConfig() {
  const { buildDocuConfig } = await import("file://${createDocuConfAbsolute}");
  const yamlContent = fs.readFileSync("${configYamlAbsolute}", "utf8");
  const rawConf = yaml.load(yamlContent);
  return buildDocuConfig(rawConf, "${UserRoot.replace(/\\/g, "/")}");
}
`;

  const shimPath = path.join(dotDir, "docusaurus.config.js");
  fs.writeFileSync(shimPath, shimContent);
  logger.debug(`Config shim written to ${shimPath}`);

  return shimPath;
}

/**
 * Validate that the current directory is a Portosaurus project.
 */
export function validateProject(UserRoot) {
  const configPath = ["config.yaml", "config.yml"].find((f) =>
    fs.existsSync(path.join(UserRoot, f)),
  );
  if (!configPath) {
    logger.log("");
    logger.error(
      "config.yml/config.yaml not found. Are you in a Portosaurus project directory?",
    );
    process.exit(1);
  }
}

/**
 * Ensure essential user content directories exist.
 */
export function ensureContentDirs(UserRoot) {
  for (const dir of ["notes", "blog", "static"]) {
    fs.mkdirSync(path.join(UserRoot, dir), { recursive: true });
  }

  const notesIndex = path.join(UserRoot, "notes", "index.mdx");
  if (!fs.existsSync(notesIndex)) {
    fs.writeFileSync(
      notesIndex,
      `---\nhide_table_of_contents: true\n---\n\nimport NoteCards from "portosaurus/src/theme/components/NoteIndex/index.js";\n\n# Notes\n\n<NoteCards />\n`,
    );
    logger.debug("Created default notes/index.mdx");
  }
}

/**
 * Spawn a Docusaurus command and wait for it to complete.
 */
export function runDocusaurus(command, extraArgs, UserRoot, configPath) {
  const { command: cmd, args: pmArgs, packageManager } = getDocuCmd(UserRoot);

  logger.info(`Running docusaurus ${command} (via ${packageManager})`);

  const finalArgs = [
    ...pmArgs,
    command,
    UserRoot,
    "--config",
    configPath,
    ...extraArgs,
  ];

  const child = spawn(cmd, finalArgs, {
    stdio: "inherit",
    cwd: UserRoot,
    env: { ...process.env, FORCE_COLOR: "true" },
  });

  return new Promise((resolve, reject) => {
    child.on("error", (err) => {
      logger.error(`Failed to run docusaurus ${command}: ${err.message}`);
      reject(err);
    });
    child.on("close", (code) => {
      if (code === 0) resolve();
      else process.exit(code);
    });
  });
}
