image: oven/bun:latest

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  script:
    - bun install
    - bun run build
    - bunx surge ./build --domain {{projectName}}.surge.sh
  variables:
    SURGE_LOGIN: $SURGE_LOGIN
    SURGE_TOKEN: $SURGE_TOKEN
