kind: pipeline
name: deploy

steps:
  - name: build
    image: oven/bun:latest
    commands:
      - bun install
      - bunx portosaur build

  - name: deploy
    image: appleboy/drone-git-push
    settings:
      branch: pages
      remote: git@codeberg.org:${DRONE_REPO}.git
      force: true
      commit: true
      path: build
    when:
      event: push
      branch: main
