name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dummy
  workflow_dispatch:  

jobs:
  build:
    name: Compile Source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm 

      - name: Install dependencies
        run: npm ci 
        
      - name: Remove old artifacts
        run: rm -rf build       

      - name: Build website
        run: npm run build 

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
