name: Deploy to GitHub Pages

on:
  push:
    branches:
      - content
  schedule:
    - cron: "0 3,15 * * *"
  workflow_dispatch:

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Restore Cached Version Info
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: .upstream-cache
          key: portosaurus-last-version

      - name: Fetch & Compare Version
        id: check
        run: |
          mkdir -p .upstream-cache

          curl -s https://raw.githubusercontent.com/soymadip/portosaurus/main/package.json \
            | jq -r .version > .upstream-cache/upstream_version.txt

          latest=$(cat .upstream-cache/upstream_version.txt)

          echo "Latest version: $latest"

          if [ -f .upstream-cache/last-version.txt ]; then

            stored=$(cat .upstream-cache/last-version.txt)
            echo "Stored version: $stored"

            if [ "$latest" = "$stored" ]; then
              echo "No version change detected."
              echo "changed=false" >> $GITHUB_OUTPUT
              exit 0
            fi
          else
            echo "No previous version stored."
          fi

          echo "Version changed!"
          echo "changed=true" >> $GITHUB_OUTPUT

      - name: Compile Docs
        if: steps.check.outputs.changed == 'true'
        run: bash ./.github/compile.sh

      - name: Update Version Cache
        if: steps.check.outputs.changed == 'true'
        run: |
          cp .upstream-cache/upstream_version.txt .upstream-cache/last-version.txt

          echo "Saving updated version cache..."

        shell: bash
        env:
          ACTIONS_CACHE_URL: ${{ runner.cacheUrl }}
          ACTIONS_RUNTIME_TOKEN: ${{ runner.token }}
        run: |
          echo "Saving cache..."
          echo "::save-state name=cache-hit::false"
        uses: actions/cache/save@v4
        with:
          path: .upstream-cache
          key: portosaurus-last-version
