name: Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/deploy-docs.yml"
      - "packages/docs/**"
      - "packages/cli/src/commands/schema.*"
      - "packages/core/src/index.mjs"
      - "package.json"
      - "bun.lock"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  DOCS_DIR: packages/docs
  DOCS_OUT_DIR: ${{ env.DOCS_DIR }}/.vitepress/dist
  CLI_DIR: packages/cli

jobs:
  deploy:
    concurrency:
      group: docs-pages
      cancel-in-progress: true

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Cache dependencies and builds
        uses: actions/cache@v5
        with:
          path: |
            ~/.bun/install/cache
            ${{ env.DOCS_DIR }}/.vitepress/cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/bun.lockb', 'packages/docs/**') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Install Dependencies
        run: |-
          bun install --cwd ${{ env.DOCS_DIR }}
          bun install --cwd ${{ env.CLI_DIR }}

      - name: Compile Site
        run: bun run --cwd ${{ env.DOCS_DIR }} build

      - name: Generate Config Schema
        run: bun run ${{ env.CLI_DIR }}/bin/porto.mjs schema -o ${{ env.DOCS_OUT_DIR }}/conf-schema.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ${{ env.DOCS_OUT_DIR }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
