name: Sync Files from compiler branch

on:
  push:
    branches:
      - compiler
    paths:
      - 'config.js'
      - '.vscode/**'
      - '.github/scripts/**'
      - '.github/config.json'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

jobs:
  sync-config:
    runs-on: ubuntu-latest
    if: github.repository == 'soymadip/portosaurus'
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: content
          fetch-depth: 0

      - name: Ensure we are on content branch
        run: git checkout content

      - name: Set up file list
        id: setup
        run: |
          CONFIG_FILE=".github/config.json"

          # Extract the files_to_sync array
          SYNC_FILES=$(jq -r '.files_to_sync | join(" ")' "$CONFIG_FILE")

          echo "SYNC_FILES=$SYNC_FILES" >> $GITHUB_ENV

      - name: Fetch and copy files from compiler branch
        run: |
          git fetch origin compiler:compiler

          IFS=' ' read -r -a file_array <<< "$SYNC_FILES"

          for file in "${file_array[@]}"; do
            if git ls-tree -r compiler --name-only | grep -q "^$file$"; then
              echo "Copying $file from complier branch"
              git checkout compiler -- "$file"
            else
              echo "File $file not found in compiler branch"
            fi
          done

      - name: Commit and push updated files
        run: |
          git config user.name "soymadip"

          git config user.email "${{ github.actor }}@users.noreply.github.com"

          IFS=' ' read -r -a file_array <<< "$SYNC_FILES"

          for file in "${file_array[@]}"; do
            git add "$file" 2>/dev/null || true
          done

          if ! git diff --staged --quiet; then
            git commit -m "Sync files from compiler branch"
            git push origin content
          else
            echo "No changes to commit"
          fi
