name: Sync Files from code branch

on:
  push:
    branches:
      - code
    paths:
      - 'config.js'
      - '.vscode/**'
      - '.github/sync-files.list'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  sync-config:
    runs-on: ubuntu-latest
    if: github.repository == 'soymadip/portosaurus'
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: content
          fetch-depth: 0

      - name: Ensure we are on content branch
        run: git checkout content

      - name: Set up file list
        id: setup
        run: |
          FILES_LIST=".github/sync-files.list"
          TEMP_FILE=$(mktemp)

          # Filter out comments and empty lines
          while IFS= read -r file || [[ -n "$file" ]]; do
            [[ -z "$file" || "$file" == \#* || "$file" == //* ]] && continue
            echo "$file" >> "$TEMP_FILE"
          done < "$FILES_LIST"

          SYNC_FILES="$(paste -sd' ' "$TEMP_FILE")"
          echo "SYNC_FILES=$SYNC_FILES" >> $GITHUB_ENV

          rm "$TEMP_FILE"

      - name: Fetch and copy files from code branch
        run: |
          git fetch origin code:code

          IFS=' ' read -r -a file_array <<< "$SYNC_FILES"

          for file in "${file_array[@]}"; do
            if git ls-tree -r code --name-only | grep -q "^$file$"; then
              echo "Copying $file from code branch"
              git checkout code -- "$file"
            else
              echo "File $file not found in code branch"
            fi
          done

      - name: Commit and push updated files
        run: |
          git config user.name "soymadip"

          git config user.email "${{ github.actor }}@users.noreply.github.com"

          IFS=' ' read -r -a file_array <<< "$SYNC_FILES"

          for file in "${file_array[@]}"; do
            git add "$file" 2>/dev/null || true
          done

          if ! git diff --staged --quiet; then
            git commit -m "Sync files from code branch"
            git push origin content
          else
            echo "No changes to commit"
          fi
